services:
  cassava-support:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cassava-support
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      # Core configuration
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      - APP_HOST=${APP_HOST:-0.0.0.0}
      - APP_PORT=${APP_PORT:-8000}
      
      # AI Models
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - MISTRAL_MODEL=${MISTRAL_MODEL:-mistral-large-latest}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama2}
      
      # Messaging platforms
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_WEBHOOK_VERIFY_TOKEN=${WHATSAPP_WEBHOOK_VERIFY_TOKEN}
      
      # Database and Storage
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@postgres:5432/support_db}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      
      # Security
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-secret-key}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-dev-webhook-secret}
      
      # CORS and API settings
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8000,http://127.0.0.1:8000}
      - ALLOWED_METHODS=${ALLOWED_METHODS:-GET,POST,PUT,DELETE,OPTIONS}
      - ALLOWED_HEADERS=${ALLOWED_HEADERS:-*}
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
      - ./backend:/app  # Backend source code
      - ./frontend:/app/static  # Frontend files served by FastAPI
    networks:
      - cassava_network
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-cassava
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - cassava_network
    restart: unless-stopped

networks:
  cassava_network:
    driver: bridge

volumes:
  app_data:
    driver: local
  app_logs:
    driver: local
  ollama_models:
    driver: local